# Part 2

### Question 1

In [1]:
# importing numpy library
import numpy as np

# Load in Y,X,L
Y = np.matrix([112, 107, 103, 91, 85, 84, 85, 79, 81, 134, 86, 99, 89, 111, 114, 118, 163, 193, 143, 144, 202, 158, 160, 144])
X = np.matrix([100, 112, 107, 103, 91, 85, 84, 85, 79, 81, 134, 86, 99, 89, 111, 114, 118, 163, 193, 143, 144, 202, 158, 160])
L = np.matrix([30, 75, 64, 41, 51, 42, 51, 57, 49, 134, 52, 99, 56, 81, 79, 73, 163, 193, 99, 91, 202, 105, 101, 96])

# Reshape Y
Y = Y.reshape(-1,1)

# Reshape L
L = L.reshape(-1,1)

# Reshape X
ones = np.ones(24).reshape(-1,1)
X = X.reshape(-1,1)
X = np.hstack((ones,X))
X = np.hstack((X,L))

In [2]:
# Calculate the value for lambda
lambda_val = np.dot(2*np.linalg.pinv(np.dot(np.dot(X,np.linalg.pinv(np.dot(X.transpose(),X))),X.transpose())),L)-2*Y

# Calculate the value for beta
beta_val = np.dot(np.linalg.pinv(np.dot(X.transpose(),X)),(np.dot(X.transpose(),Y)+np.dot(0.5*X.transpose(),lambda_val)))

In [3]:
# Print Reshaped Y
print("!!!!!Reshaped Y value!!!!!")
Y 

!!!!!Reshaped Y value!!!!!


matrix([[112],
        [107],
        [103],
        [ 91],
        [ 85],
        [ 84],
        [ 85],
        [ 79],
        [ 81],
        [134],
        [ 86],
        [ 99],
        [ 89],
        [111],
        [114],
        [118],
        [163],
        [193],
        [143],
        [144],
        [202],
        [158],
        [160],
        [144]])

In [4]:
# Print reshaped L
print("!!!!!Reshaped L value!!!!!")
L

!!!!!Reshaped L value!!!!!


matrix([[ 30],
        [ 75],
        [ 64],
        [ 41],
        [ 51],
        [ 42],
        [ 51],
        [ 57],
        [ 49],
        [134],
        [ 52],
        [ 99],
        [ 56],
        [ 81],
        [ 79],
        [ 73],
        [163],
        [193],
        [ 99],
        [ 91],
        [202],
        [105],
        [101],
        [ 96]])

In [5]:
# Print reshaped X
print("!!!!!Reshaped X value!!!!!")
X

!!!!!Reshaped X value!!!!!


matrix([[  1., 100.,  30.],
        [  1., 112.,  75.],
        [  1., 107.,  64.],
        [  1., 103.,  41.],
        [  1.,  91.,  51.],
        [  1.,  85.,  42.],
        [  1.,  84.,  51.],
        [  1.,  85.,  57.],
        [  1.,  79.,  49.],
        [  1.,  81., 134.],
        [  1., 134.,  52.],
        [  1.,  86.,  99.],
        [  1.,  99.,  56.],
        [  1.,  89.,  81.],
        [  1., 111.,  79.],
        [  1., 114.,  73.],
        [  1., 118., 163.],
        [  1., 163., 193.],
        [  1., 193.,  99.],
        [  1., 143.,  91.],
        [  1., 144., 202.],
        [  1., 202., 105.],
        [  1., 158., 101.],
        [  1., 160.,  96.]])

In [6]:
# Print lambda value
print("!!!!!Lambda value!!!!!")
lambda_val

!!!!!Lambda value!!!!!


matrix([[-1.64000000e+02],
        [-6.40000000e+01],
        [-7.80000000e+01],
        [-1.00000000e+02],
        [-6.80000000e+01],
        [-8.40000000e+01],
        [-6.80000000e+01],
        [-4.40000000e+01],
        [-6.40000000e+01],
        [ 2.50111043e-12],
        [-6.80000000e+01],
        [ 2.50111043e-12],
        [-6.60000000e+01],
        [-6.00000000e+01],
        [-7.00000000e+01],
        [-9.00000000e+01],
        [ 4.54747351e-13],
        [-2.04636308e-12],
        [-8.80000000e+01],
        [-1.06000000e+02],
        [-1.19371180e-12],
        [-1.06000000e+02],
        [-1.18000000e+02],
        [-9.60000000e+01]])

In [7]:
# Print beta value
print("!!!!!Beta value!!!!!")
beta_val

!!!!!Beta value!!!!!


matrix([[ 3.41060513e-13],
        [-1.77635684e-15],
        [ 1.00000000e+00]])

In [8]:
# Change the negative lambda value to zero, and keep the positive lambda value
new_lambda = np.matrix([0,0,0,0,0,0,0,0,0,2.50111043e-12,0,2.50111043e-12,0,0,0,0,4.54747351e-13,0,0,0,0,0,0,0]).reshape(-1,1)

# Print new_lambda
print("!!!!!New lambda value!!!!!")
new_lambda

!!!!!New lambda value!!!!!


matrix([[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [2.50111043e-12],
        [0.00000000e+00],
        [2.50111043e-12],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [4.54747351e-13],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]])

In [9]:
# Calculate new beta
new_beta = np.dot(np.linalg.pinv(np.dot(X.transpose(),X)),(np.dot(X.transpose(),Y)+np.dot(0.5*X.transpose(),new_lambda)))

# Print new_beta
print("!!!!!New beta value!!!!!")
new_beta

!!!!!New beta value!!!!!


matrix([[26.55664032],
        [ 0.37819647],
        [ 0.5629484 ]])

In [10]:
prediction = np.dot(X,new_beta)
print("!!!!!Prediction!!!!!")
prediction

!!!!!Prediction!!!!!


matrix([[ 81.26473915],
        [111.13577478],
        [103.05236003],
        [ 88.59176095],
        [ 89.68288734],
        [ 82.34717293],
        [ 87.03551206],
        [ 90.79139893],
        [ 84.01863292],
        [132.62563988],
        [106.50828387],
        [114.81342821],
        [ 95.52320109],
        [105.81494641],
        [113.00937191],
        [110.76627091],
        [162.94441281],
        [196.85170589],
        [155.28045031],
        [131.8670397 ],
        [194.7325086 ],
        [162.06190892],
        [143.16947072],
        [141.11112166]])