# Part 1

## Question 1

### Part A

In [1]:
# importing numpy library
import numpy as np
  
# create matrix B
b = np.array([[1, 2, -1],
              [-1, 1, 2],
              [0, 1, 1]])
  
print("Matrix B:\n",b)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(b)
  
# printing eigen values
print("Eigenvalues of matrix B:\n",w)
  
# printing eigen vectors
print("Eigenvectors of matrix B:\n",v)

Matrix B:
 [[ 1  2 -1]
 [-1  1  2]
 [ 0  1  1]]
Eigenvalues of matrix B:
 [0.5+0.8660254j 0.5-0.8660254j 2. +0.j       ]
Eigenvectors of matrix B:
 [[ 0.8819171 +0.j          0.8819171 -0.j          0.57735027+0.j        ]
 [-0.06299408+0.32732684j -0.06299408-0.32732684j  0.57735027+0.j        ]
 [ 0.31497039-0.10910895j  0.31497039+0.10910895j  0.57735027+0.j        ]]


### Part B 

In [2]:
# Calculate X inverse
inv_X = np.linalg.inv(v)

# Calculate diagnoal matrix
Λ = np.diag(w)

# Calculate invert Λ
inv_Λ = np.linalg.inv(Λ)

# Check with the actual inverse
print("Actual inverse of matrix B:\n",np.linalg.inv(b))

Actual inverse of matrix B:
 [[-0.5 -1.5  2.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5  1.5]]


In [3]:
# Calculate invert matrix B
inv_B = np.linalg.pinv(np.dot(np.dot(v,Λ),inv_X))
print("Calculate inverse by using eign decomposition formula:\n", inv_B)

Calculate inverse by using eign decomposition formula:
 [[-0.5+1.31838984e-16j -1.5+1.17961196e-16j  2.5-3.53883589e-16j]
 [ 0.5-3.46944695e-17j  0.5-1.04083409e-16j -0.5+2.01227923e-16j]
 [-0.5+2.08166817e-17j -0.5+6.93889390e-18j  1.5-7.63278329e-17j]]


## Question 2

### Part A

In [4]:
# Importing Packages
import numpy as np
import matplotlib.pyplot as plt

# Defining Equation and Derivative
def f(x):
    res = 16*x**3 + 8*x-20
    return res
 
def dfdx(x):
    res = 48*x**2 + 8
    return res

# Newton-Raphson Algorithm
def Newton_Method(tol,x0):
    max_iter = 10  # Max iterations
    i = 0  # Iteration counter
    xi_1 = x0
    print('Iteration' + str(i) +  ': x = ' + str(x0) + ', f(x) = ' + str(f(x0)))
    # Iterating until either the tolerance or max iterations is met
    while abs(f(xi_1)) > tol or i > max_iter:
        i = i + 1
        xi = xi_1-f(xi_1)/dfdx(xi_1)  # Newton-Raphson equation
        print('Iteration' + str(i) + ': x = ' + str(xi) + ', f(x) = ' + str(f(xi)))
        xi_1 = xi 
    print("The local minimum is", xi)

### Part B

In [5]:
def Gradient_Descent(precision, rate, cur_x): #tolerance, learning_rate, initial_val
    previous_step_size = 1 
    max_iters = 10000 # maximum number of iterations
    iters = 0 #iteration counter
    df = lambda x: 16*x**3+8*x-20 #Gradient of our function 

    while previous_step_size > precision and iters < max_iters:
        prev_x = cur_x #Store current x value in prev_x
        cur_x = cur_x - rate * df(prev_x) #Grad descent
        previous_step_size = abs(cur_x - prev_x) #Change in x
        iters = iters+1 #iteration count
    print("Iteration",iters) #Print iterations   
    print("The local minimum occurs at", cur_x)

### Part C

In [6]:
# Newton-Raphson Algorithm
print("!!!!!Newton's method!!!!!")
Newton_Method(0.00001,1)

!!!!!Newton's method!!!!!
Iteration0: x = 1, f(x) = 4
Iteration1: x = 0.9285714285714286, f(x) = 0.23906705539358697
Iteration2: x = 0.9237308146399056, f(x) = 0.001042562586704321
Iteration3: x = 0.9237095193270902, f(x) = 2.010718702649683e-08
The local minimum is 0.9237095193270902


In [7]:
# Gradient descent
print("!!!!!Gradient descent!!!!!")
Gradient_Descent(0.00001, 0.01, 1)

!!!!!Gradient descent!!!!!
Iteration 14
The local minimum occurs at 0.9237149544016079
